#!/bin/bash -l

#SBATCH --nodes              1

#SBATCH --ntasks             1
#SBATCH --cpus-per-task      8
#SBATCH --partition gpu  
#SBATCH --qos gpu 
#SBATCH --gres gpu:1
#SBATCH --time 24:00:00


python3 -m monstereo.run eval --dir_ann data/kitti-pifpaf/annotations --model nope  --model_mono data/models/ms-201207-194659-transformer-kitti.pkl --generate --save --verbose --confidence --transformer
