#!/bin/bash -l

#SBATCH --nodes              1

#SBATCH --ntasks             1
#SBATCH --cpus-per-task      8
#SBATCH --partition gpu  

#SBATCH --qos gpu 
#SBATCH --gres gpu:1
#SBATCH --time 24:00:00

lines=('000005.png' '000021.png' '000025.png' '000107.png' '000117.png'  '000135.png' '000168.png')

len=${#lines[@]}


for ((j=0;j<"$len";j++)); do

    line=${lines[j]}
    export process_mode='mean'
        python3 -m  monstereo.run predict /home/bonnesoe/data/kitti/training/image_2/$line --joints_folder data/kitti-pifpaf/annotations_car --mode mono --model data/models/ms-201111-221611-vehicles-kitti.pkl --output_types combined_nkps --vehicles --path_gt data/arrays/names-kitti--vehicles-201111-221406.json --draw_box --z_max 70 --output-directory export/no_conf

        python3 -m  monstereo.run predict /home/bonnesoe/data/kitti/training/image_2/$line --joints_folder data/kitti-pifpaf/annotations_car_loose --mode mono --model data/models/ms-201111-222759-vehicles-kitti.pkl --output_types combined_nkps --vehicles --path_gt data/arrays/names-kitti--vehicles-201111-222219.json --draw_box --z_max 70 --output-directory export/no_conf_loose

        python3 -m  monstereo.run predict /home/bonnesoe/data/kitti/training/image_2/$line --joints_folder data/kitti-pifpaf/annotations_car --mode mono --model data/models/ms-201112-010729-vehicles-kitti.pkl --output_types combined_nkps --vehicles --path_gt data/arrays/names-kitti--vehicles-201112-010531.json --draw_box --z_max 70 --confidence --output-directory export/conf

        python3 -m  monstereo.run predict /home/bonnesoe/data/kitti/training/image_2/$line --joints_folder data/kitti-pifpaf/annotations_car_loose --mode mono --model data/models/ms-201112-011902-vehicles-kitti.pkl --output_types combined_nkps --vehicles --path_gt data/arrays/names-kitti--vehicles-201112-011330.json --draw_box --z_max 70 --confidence --output-directory export/conf_loose

        python3 -m  monstereo.run predict /home/bonnesoe/data/kitti/training/image_2/$line --joints_folder data/kitti-pifpaf/annotations_car --mode mono --model data/models/ms-201111-221611-vehicles-kitti.pkl --output_types combined_kps --vehicles --path_gt data/arrays/names-kitti--vehicles-201111-221406.json --draw_box --z_max 70 --output-directory export/no_conf

        python3 -m  monstereo.run predict /home/bonnesoe/data/kitti/training/image_2/$line --joints_folder data/kitti-pifpaf/annotations_car_loose --mode mono --model data/models/ms-201111-222759-vehicles-kitti.pkl --output_types combined_kps --vehicles --path_gt data/arrays/names-kitti--vehicles-201111-222219.json --draw_box --z_max 70 --output-directory export/no_conf_loose

        python3 -m  monstereo.run predict /home/bonnesoe/data/kitti/training/image_2/$line --joints_folder data/kitti-pifpaf/annotations_car --mode mono --model data/models/ms-201112-010729-vehicles-kitti.pkl --output_types combined_kps --vehicles --path_gt data/arrays/names-kitti--vehicles-201112-010531.json --draw_box --z_max 70 --confidence --output-directory export/conf

        python3 -m  monstereo.run predict /home/bonnesoe/data/kitti/training/image_2/$line --joints_folder data/kitti-pifpaf/annotations_car_loose --mode mono --model data/models/ms-201112-011902-vehicles-kitti.pkl --output_types combined_kps --vehicles --path_gt data/arrays/names-kitti--vehicles-201112-011330.json --draw_box --z_max 70 --confidence --output-directory export/conf_loose

done