#!/bin/bash -l

#SBATCH --nodes              1

#SBATCH --ntasks             1
#SBATCH --cpus-per-task      3
#SBATCH --partition gpu  
#SBATCH --reservation=vita-2020-11 
#SBATCH --qos gpu 
#SBATCH --gres gpu:1
#SBATCH --time 08:00:00

dir_ann_car='data/kitti-pifpaf/annotations_car'

output_type='combined_3d'

num_images='70'

args="--z_max 50 --confidence"

input="splits/kitti_val.txt"

dataset="kitti"

process_modes=("NULL_ISNT_IT" "neg" "mean" "mean_std")
len=${#process_modes[@]}


output_dirs=('visual_tests_conf/val_kitti' 'visual_tests_conf/val_kitti_neg'  'visual_tests_conf/val_kitti_mean' 'visual_tests_conf/val_kitti_mean_std')
models=('data/models/ms-201111-174756-vehicles-kitti.pkl' 'data/models/ms-201111-182203-vehicles-kitti.pkl' 'data/models/ms-201111-185643-vehicles-kitti.pkl' 'data/models/ms-201111-193141-vehicles-kitti.pkl')
names_gt=('data/arrays/names-kitti--vehicles-201111-174409.json' 'data/arrays/names-kitti--vehicles-201111-181811.json' 'data/arrays/names-kitti--vehicles-201111-185251.json' 'data/arrays/names-kitti--vehicles-201111-192727.json')

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done


#Loop for the dropout

output_dirs=( 'visual_tests_conf/val_kitti_drop' 'visual_tests_conf/val_kitti_neg_drop' 'visual_tests_conf/val_kitti_mean_drop' 'visual_tests_conf/val_kitti_mean_std_drop')
names_gt=('data/arrays/names-kitti--vehicles-201111-234224.json' 'data/arrays/names-kitti--vehicles-201112-002218.json' 'data/arrays/names-kitti--vehicles-201112-010531.json' 'data/arrays/names-kitti--vehicles-201112-014459.json')
models=('data/models/ms-201111-234445-vehicles-kitti.pkl' 'data/models/ms-201112-002406-vehicles-kitti.pkl' 'data/models/ms-201112-010729-vehicles-kitti.pkl' 'data/models/ms-201112-014736-vehicles-kitti.pkl')
for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done

#Loop for the loose

dir_ann_car='data/kitti-pifpaf/annotations_car_loose'
output_dirs=('visual_tests_conf/val_kitti1' 'visual_tests_conf/val_kitti_neg1' 'visual_tests_conf/val_kitti_mean1' 'visual_tests_conf/val_kitti_mean_std1')
names_gt=('data/arrays/names-kitti--vehicles-201111-175118.json' 'data/arrays/names-kitti--vehicles-201111-182530.json' 'data/arrays/names-kitti--vehicles-201111-190010.json' 'data/arrays/names-kitti--vehicles-201111-193604.json')
models=('data/models/ms-201111-175515-vehicles-kitti.pkl' 'data/models/ms-201111-182930-vehicles-kitti.pkl' 'data/models/ms-201111-190407-vehicles-kitti.pkl' 'data/models/ms-201111-194033-vehicles-kitti.pkl')


for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done

#Loop for the loose dropout

output_dirs=('visual_tests_conf/val_kitti_drop1'  'visual_tests_conf/val_kitti_neg_drop1'  'visual_tests_conf/val_kitti_mean_drop1' 'visual_tests_conf/val_kitti_mean_std_drop1')
names_gt=('data/arrays/names-kitti--vehicles-201111-235038.json' 'data/arrays/names-kitti--vehicles-201112-003006.json' 'data/arrays/names-kitti--vehicles-201112-011330.json' 'data/arrays/names-kitti--vehicles-201112-015421.json')
models=('data/models/ms-201111-235550-vehicles-kitti.pkl' 'data/models/ms-201112-003521-vehicles-kitti.pkl' 'data/models/ms-201112-011902-vehicles-kitti.pkl' 'data/models/ms-201112-020007-vehicles-kitti.pkl')

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done



###############################################################################################

output_type='combined_kps'



output_dirs=('visual_tests_conf/val_kitti' 'visual_tests_conf/val_kitti_neg'  'visual_tests_conf/val_kitti_mean' 'visual_tests_conf/val_kitti_mean_std')
models=('data/models/ms-201111-174756-vehicles-kitti.pkl' 'data/models/ms-201111-182203-vehicles-kitti.pkl' 'data/models/ms-201111-185643-vehicles-kitti.pkl' 'data/models/ms-201111-193141-vehicles-kitti.pkl')
names_gt=('data/arrays/names-kitti--vehicles-201111-174409.json' 'data/arrays/names-kitti--vehicles-201111-181811.json' 'data/arrays/names-kitti--vehicles-201111-185251.json' 'data/arrays/names-kitti--vehicles-201111-192727.json')

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done


#Loop for the dropout

output_dirs=( 'visual_tests_conf/val_kitti_drop' 'visual_tests_conf/val_kitti_neg_drop' 'visual_tests_conf/val_kitti_mean_drop' 'visual_tests_conf/val_kitti_mean_std_drop')
names_gt=('data/arrays/names-kitti--vehicles-201111-234224.json' 'data/arrays/names-kitti--vehicles-201112-002218.json' 'data/arrays/names-kitti--vehicles-201112-010531.json' 'data/arrays/names-kitti--vehicles-201112-014459.json')
models=('data/models/ms-201111-234445-vehicles-kitti.pkl' 'data/models/ms-201112-002406-vehicles-kitti.pkl' 'data/models/ms-201112-010729-vehicles-kitti.pkl' 'data/models/ms-201112-014736-vehicles-kitti.pkl')
for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done

#Loop for the loose

dir_ann_car='data/kitti-pifpaf/annotations_car_loose'
output_dirs=('visual_tests_conf/val_kitti1' 'visual_tests_conf/val_kitti_neg1' 'visual_tests_conf/val_kitti_mean1' 'visual_tests_conf/val_kitti_mean_std1')
names_gt=('data/arrays/names-kitti--vehicles-201111-175118.json' 'data/arrays/names-kitti--vehicles-201111-182530.json' 'data/arrays/names-kitti--vehicles-201111-190010.json' 'data/arrays/names-kitti--vehicles-201111-193604.json')
models=('data/models/ms-201111-175515-vehicles-kitti.pkl' 'data/models/ms-201111-182930-vehicles-kitti.pkl' 'data/models/ms-201111-190407-vehicles-kitti.pkl' 'data/models/ms-201111-194033-vehicles-kitti.pkl')


for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done

#Loop for the loose dropout

output_dirs=('visual_tests_conf/val_kitti_drop1'  'visual_tests_conf/val_kitti_neg_drop1'  'visual_tests_conf/val_kitti_mean_drop1' 'visual_tests_conf/val_kitti_mean_std_drop1')
names_gt=('data/arrays/names-kitti--vehicles-201111-235038.json' 'data/arrays/names-kitti--vehicles-201112-003006.json' 'data/arrays/names-kitti--vehicles-201112-011330.json' 'data/arrays/names-kitti--vehicles-201112-015421.json')
models=('data/models/ms-201111-235550-vehicles-kitti.pkl' 'data/models/ms-201112-003521-vehicles-kitti.pkl' 'data/models/ms-201112-011902-vehicles-kitti.pkl' 'data/models/ms-201112-020007-vehicles-kitti.pkl')

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done



############################################################################################################

output_type='combined_nkps'


output_dirs=('visual_tests_conf/val_kitti' 'visual_tests_conf/val_kitti_neg'  'visual_tests_conf/val_kitti_mean' 'visual_tests_conf/val_kitti_mean_std')
models=('data/models/ms-201111-174756-vehicles-kitti.pkl' 'data/models/ms-201111-182203-vehicles-kitti.pkl' 'data/models/ms-201111-185643-vehicles-kitti.pkl' 'data/models/ms-201111-193141-vehicles-kitti.pkl')
names_gt=('data/arrays/names-kitti--vehicles-201111-174409.json' 'data/arrays/names-kitti--vehicles-201111-181811.json' 'data/arrays/names-kitti--vehicles-201111-185251.json' 'data/arrays/names-kitti--vehicles-201111-192727.json')

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done


#Loop for the dropout

output_dirs=( 'visual_tests_conf/val_kitti_drop' 'visual_tests_conf/val_kitti_neg_drop' 'visual_tests_conf/val_kitti_mean_drop' 'visual_tests_conf/val_kitti_mean_std_drop')
names_gt=('data/arrays/names-kitti--vehicles-201111-234224.json' 'data/arrays/names-kitti--vehicles-201112-002218.json' 'data/arrays/names-kitti--vehicles-201112-010531.json' 'data/arrays/names-kitti--vehicles-201112-014459.json')
models=('data/models/ms-201111-234445-vehicles-kitti.pkl' 'data/models/ms-201112-002406-vehicles-kitti.pkl' 'data/models/ms-201112-010729-vehicles-kitti.pkl' 'data/models/ms-201112-014736-vehicles-kitti.pkl')
for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done

#Loop for the loose

dir_ann_car='data/kitti-pifpaf/annotations_car_loose'
output_dirs=('visual_tests_conf/val_kitti1' 'visual_tests_conf/val_kitti_neg1' 'visual_tests_conf/val_kitti_mean1' 'visual_tests_conf/val_kitti_mean_std1')
names_gt=('data/arrays/names-kitti--vehicles-201111-175118.json' 'data/arrays/names-kitti--vehicles-201111-182530.json' 'data/arrays/names-kitti--vehicles-201111-190010.json' 'data/arrays/names-kitti--vehicles-201111-193604.json')
models=('data/models/ms-201111-175515-vehicles-kitti.pkl' 'data/models/ms-201111-182930-vehicles-kitti.pkl' 'data/models/ms-201111-190407-vehicles-kitti.pkl' 'data/models/ms-201111-194033-vehicles-kitti.pkl')


for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done

#Loop for the loose dropout

output_dirs=('visual_tests_conf/val_kitti_drop1'  'visual_tests_conf/val_kitti_neg_drop1'  'visual_tests_conf/val_kitti_mean_drop1' 'visual_tests_conf/val_kitti_mean_std_drop1')
names_gt=('data/arrays/names-kitti--vehicles-201111-235038.json' 'data/arrays/names-kitti--vehicles-201112-003006.json' 'data/arrays/names-kitti--vehicles-201112-011330.json' 'data/arrays/names-kitti--vehicles-201112-015421.json')
models=('data/models/ms-201111-235550-vehicles-kitti.pkl' 'data/models/ms-201112-003521-vehicles-kitti.pkl' 'data/models/ms-201112-011902-vehicles-kitti.pkl' 'data/models/ms-201112-020007-vehicles-kitti.pkl')

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done
