#!/bin/bash -l

#SBATCH --nodes              1

#SBATCH --ntasks             1
#SBATCH --cpus-per-task      3
#SBATCH --partition gpu  
#SBATCH --reservation=vita-2020-11 
#SBATCH --qos gpu 
#SBATCH --gres gpu:1
#SBATCH --time 08:00:00

dir_ann_car='data/kitti-pifpaf/annotations_car'
output_dir='visual_tests/val_kitti_mean_std'
model='data/models/ms-201104-212322-vehicles-kitti.pkl'


num_images='70'



input="splits/kitti_val.txt"

dataset="kitti"

args="--z_max 50 --draw_box"

process_modes=("NULL_ISNT_IT" "neg" "mean" "mean_std")

len=${#process_modes[@]}


output_type='combined_kps'


output_dirs=('visual_tests/val_kitti' 'visual_tests/val_kitti_neg'  'visual_tests/val_kitti_mean' 'visual_tests/val_kitti_mean_std')
models=('data/models/ms-201111-152521-vehicles-kitti.pkl' 'data/models/ms-201111-160101-vehicles-kitti.pkl' 'data/models/ms-201111-163500-vehicles-kitti.pkl' 'data/models/ms-201111-170948-vehicles-kitti.pkl')
names_gt=('data/arrays/names-kitti--vehicles-201111-152122.json' 'data/arrays/names-kitti--vehicles-201111-155711.json' 'data/arrays/names-kitti--vehicles-201111-163111.json' 'data/arrays/names-kitti--vehicles-201111-170541.json')


len=${#process_modes[@]}

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done


#Loop for the dropout

output_dirs=( 'visual_tests/val_kitti_drop' 'visual_tests/val_kitti_neg_drop' 'visual_tests/val_kitti_mean_drop' 'visual_tests/val_kitti_mean_std_drop')
names_gt=('data/arrays/names-kitti--vehicles-201111-201523.json' 'data/arrays/names-kitti--vehicles-201111-211638.json' 'data/arrays/names-kitti--vehicles-201111-221406.json' 'data/arrays/names-kitti--vehicles-201111-225735.json' 'data/arrays/names-kitti--vehicles-201112-150703.json')
models=('data/models/ms-201111-202253-vehicles-kitti.pkl' 'data/models/ms-201111-212503-vehicles-kitti.pkl' 'data/models/ms-201111-221611-vehicles-kitti.pkl' 'data/models/ms-201111-230024-vehicles-kitti.pkl' 'data/models/ms-201112-151255-vehicles-kitti.pkl')

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done

#Loop for the loose

dir_ann_car='data/kitti-pifpaf/annotations_car_loose'
output_dirs=('visual_tests/val_kitti1' 'visual_tests/val_kitti_neg1' 'visual_tests/val_kitti_mean1' 'visual_tests/val_kitti_mean_std1')
names_gt=('data/arrays/names-kitti--vehicles-201111-152918.json' 'data/arrays/names-kitti--vehicles-201111-160424.json' 'data/arrays/names-kitti--vehicles-201111-163824.json' 'data/arrays/names-kitti--vehicles-201111-171411.json')
models=('data/models/ms-201111-153330-vehicles-kitti.pkl' 'data/models/ms-201111-160821-vehicles-kitti.pkl' 'data/models/ms-201111-164220-vehicles-kitti.pkl' 'data/models/ms-201111-171825-vehicles-kitti.pkl')


for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done

#Loop for the loose dropout

output_dirs=('visual_tests/val_kitti_drop1'  'visual_tests/val_kitti_neg_drop1'  'visual_tests/val_kitti_mean_drop1' 'visual_tests/val_kitti_mean_std_drop1')
names_gt=('data/arrays/names-kitti--vehicles-201111-202848.json' 'data/arrays/names-kitti--vehicles-201111-213201.json' 'data/arrays/names-kitti--vehicles-201111-222219.json' 'data/arrays/names-kitti--vehicles-201111-230658.json')
models=('data/models/ms-201111-203550-vehicles-kitti.pkl' 'data/models/ms-201111-214019-vehicles-kitti.pkl' 'data/models/ms-201111-222759-vehicles-kitti.pkl' 'data/models/ms-201111-231315-vehicles-kitti.pkl')

for ((j=0;j<"$len";j++)); do
    echo $i ${output_dirs[j]} ${process_modes[j]} ${models[j]} ${names_gt[j]}
    export process_mode=${process_modes[j]}
    output_dir=${output_dirs[j]}
    model=${models[j]}
    name_gt=${names_gt[j]}
    echo "./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} ${args} ${num_images} ${input} ${dataset}"

    source ./predict_imgs.sh ${model} ${name_gt} ${dir_ann_car} ${output_dir} ${output_type} "${args}" ${num_images}  ${input} ${dataset}
done